name: Build and publish Docker image to the Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t walrusinho/trist:latest .

      - name: Log in to the Docker Hub
        uses: docker/login-action@v2
        with:
          token:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push image to the Docker Hub
        run: docker push walrusinho/trist:latest
